### PR TITLE
Add remark for java 11

### PR DESCRIPTION
**Pull request by achawki**

### CODE REVIEW

**Comment by nickcaballero** [comment]
Question about this - what exactly is not supported under Java 11? And does that mean that versions > Java 11 are also not supported?

**Comment by achawki** [comment]
I cloned the repo, executed the unit tests and got following error:
```
java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlElement
```
Hence I mentioned java 11 is not supported. Not sure about other versions.

Closing PR since it might create more confusion.

**Comment by nickcaballero** [comment]
@achawki I see. That makes sense - JAXB is no longer part of Java 11. Maybe it would make more sense to add the JAXB libraries as a dependency here? https://stackoverflow.com/a/52502208

**Comment by achawki** [comment]
That would definitely make sense. There may, however be more adaptations necessary.

**Pull request closed without merging**
