### PR TITLE
Allow setting RequestOptions for Checkout captures, cancels, refunds, reversals, and payment amount updates

### PR DESCRIPTION
**Pull request by jrparker**
**Description**
This change enables setting a `RequestOptions` object, which provides the `Idempotency-Key` header value, for Checkout API actions for payment captures, cancels, refunds, and reversals, along with payment amount updates.

I followed a similar pattern that [exists for the payments action](https://github.com/Adyen/adyen-java-api-library/blob/b52d7a91fa9551f4d3ed9eddf477e0e9d60fca08/src/main/java/com/adyen/service/Checkout.java#L114-L124), which is overloaded to accept a `RequestOptions` object. I have overloaded the existing methods, providing the ability to set a `RequestOptions` object for the API call.

All of the actions I updated all have the `Idempotency-Key` header listed in [Adyen's API Explorer](https://docs.adyen.com/api-explorer/Checkout/69/post/payments/_paymentPspReference_/captures).

**Tested scenarios**

**Fixed issue**:

### CODE REVIEW

**Comment by jrparker** [comment]
Hello, is this something that could be looked at for the next release? Thank you

**Comment by jrparker** [comment]
Hi @AlexandrosMor, @Morerice, @michaelpaul, and @wboereboom - can this be looked at for inclusion in a future release? Thank you.

**Comment by wboereboom** [comment]
Hey @jrparker,

Sorry for the slow response, and thanks for contributing.
We've been doing some serious overhauls on library automation, hence our slow response. I'll discuss your proposed changes to the team, but from the get-go they look legit to me.

Kind Regards,
Wouter
Adyen

**Review by michaelpaul — APPROVED** [review]
Hello @jrparker, thanks for submitting your contribution!

**Pull request merged**
